server {
    listen 8080;

    root /repo/packages/skeleton/public;
    index index.php;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /repo/packages/skeleton/public/index.php;
        include fastcgi_params;
    }
}
